/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arabaotomasyon;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;
import java.util.Date;
import java.awt.print.*;

/**
 *
 * @author SuleymanSardogan
 */
public class Rents extends javax.swing.JFrame {

    /**
     * Creates new form Rents
     */
    public Rents() {
        initComponents();
        DisplayCars();
        GetCustomers();
        DisplayRents();
    }
     Connection connection = null;
    Statement statement = null;
    ResultSet result_set = null;
    //Showing Cars Table
    private void DisplayCars(){    
     String car_status = "Available";
       try{ 
        connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/cardb","root","123456s.");
        statement = connection.createStatement();
        result_set = statement.executeQuery("select * from cartbl where status='"+car_status+"'");
        CarsTable.setModel(DbUtils.resultSetToTableModel(result_set));
        
          }
       catch(SQLException e){
           e.printStackTrace();
       }
    }
    
    //showing rented car
     private void DisplayRents(){        
       try{ 
        connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/cardb","root","123456s.");
        statement = connection.createStatement();
        result_set = statement.executeQuery("select * from renttbl");
        RentTable.setModel(DbUtils.resultSetToTableModel(result_set));
        
          }
       catch(SQLException e){
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        FeesTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Cars = new javax.swing.JLabel();
        Customer = new javax.swing.JLabel();
        LogOut1 = new javax.swing.JLabel();
        ReturnCar = new javax.swing.JLabel();
        CustomerNameComboBox = new javax.swing.JComboBox<>();
        RegTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        RentsSaveBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        RentIdTxt = new javax.swing.JTextField();
        RentsEditBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CarsTable = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        RentsResetBtn = new javax.swing.JButton();
        RentDate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ReturnDate = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        RentTable = new javax.swing.JTable();
        RentsPrintBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("Fees");

        FeesTxt.setBackground(new java.awt.Color(255, 255, 255));
        FeesTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("-");

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("Cars Rental");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("Customer Name");

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));

        Cars.setBackground(new java.awt.Color(204, 0, 0));
        Cars.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Cars.setForeground(new java.awt.Color(255, 255, 255));
        Cars.setText("Cars");
        Cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsMouseClicked(evt);
            }
        });

        Customer.setBackground(new java.awt.Color(204, 0, 0));
        Customer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Customer.setForeground(new java.awt.Color(255, 255, 255));
        Customer.setText("Customer ");
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });

        LogOut1.setBackground(new java.awt.Color(204, 0, 0));
        LogOut1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setText("LogOut");
        LogOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut1MouseClicked(evt);
            }
        });

        ReturnCar.setBackground(new java.awt.Color(204, 0, 0));
        ReturnCar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ReturnCar.setForeground(new java.awt.Color(255, 255, 255));
        ReturnCar.setText("Return Car");
        ReturnCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnCarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOut1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addComponent(Cars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Customer, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cars, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnCar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CustomerNameComboBox.setBackground(new java.awt.Color(255, 255, 255));
        CustomerNameComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CustomerNameComboBox.setForeground(new java.awt.Color(0, 0, 0));

        RegTxt.setBackground(new java.awt.Color(255, 255, 255));
        RegTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("Registration");

        RentsSaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        RentsSaveBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RentsSaveBtn.setForeground(new java.awt.Color(204, 0, 0));
        RentsSaveBtn.setText("Save");
        RentsSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentsSaveBtnActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Cars List");

        RentIdTxt.setBackground(new java.awt.Color(255, 255, 255));
        RentIdTxt.setForeground(new java.awt.Color(0, 0, 0));

        RentsEditBtn.setBackground(new java.awt.Color(255, 255, 255));
        RentsEditBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RentsEditBtn.setForeground(new java.awt.Color(204, 0, 0));
        RentsEditBtn.setText("Edit");
        RentsEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentsEditBtnActionPerformed(evt);
            }
        });

        CarsTable.setAutoCreateRowSorter(true);
        CarsTable.setBackground(new java.awt.Color(204, 204, 204));
        CarsTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        CarsTable.setForeground(new java.awt.Color(0, 0, 0));
        CarsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Registiration", "Brand", "Model", "Status", "Price"
            }
        ));
        CarsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CarsTable);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 204, 204));
        jLabel24.setText("Rent Id");

        RentsResetBtn.setBackground(new java.awt.Color(255, 255, 255));
        RentsResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RentsResetBtn.setForeground(new java.awt.Color(204, 0, 0));
        RentsResetBtn.setText("Reset");
        RentsResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentsResetBtnActionPerformed(evt);
            }
        });

        RentDate.setBackground(new java.awt.Color(255, 255, 255));
        RentDate.setForeground(new java.awt.Color(0, 0, 0));
        RentDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Rent Date");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 204));
        jLabel15.setText("Return Date");

        ReturnDate.setBackground(new java.awt.Color(255, 255, 255));
        ReturnDate.setForeground(new java.awt.Color(0, 0, 0));
        ReturnDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("Cars On Rent");

        RentTable.setAutoCreateRowSorter(true);
        RentTable.setBackground(new java.awt.Color(204, 204, 204));
        RentTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        RentTable.setForeground(new java.awt.Color(0, 0, 0));
        RentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "RentId", "Registration", "Customer", "RentDate", "ReturnDate", "Fees"
            }
        ));
        RentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(RentTable);

        RentsPrintBtn.setBackground(new java.awt.Color(255, 255, 255));
        RentsPrintBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RentsPrintBtn.setForeground(new java.awt.Color(204, 0, 0));
        RentsPrintBtn.setText("Print");
        RentsPrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentsPrintBtnActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 204));
        jLabel17.setText("Fees");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(RentsPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(RegTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(CustomerNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(RentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(RentsSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(RentsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RentsResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(426, 426, 426)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(452, 452, 452)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(225, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RegTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RentIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CustomerNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RentsSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RentsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RentsResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RentsPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //for showing customers
    private void GetCustomers()
    { 
        try{
        connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/cardb","root","123456s.");
        statement = connection.createStatement();
        String query="select * from customertbl";
        result_set = statement.executeQuery(query);
        while(result_set.next()){
            String Customer = result_set.getString("CustomerName");
            CustomerNameComboBox.addItem(Customer);
            
        }
        
    }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        
    }
    private void CarsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsTableMouseClicked
         //I did not want to write User.It is like hard to write just click the cars and press delete button puff
         DefaultTableModel model = (DefaultTableModel)CarsTable.getModel();
         int MyIndex = CarsTable.getSelectedRow();
      
         RegTxt.setText(model.getValueAt(MyIndex,0).toString());

    }//GEN-LAST:event_CarsTableMouseClicked

    private void RentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentTableMouseClicked
          
       //I did not want to write User.It is like hard to write just click the cars and press delete button puff
       DefaultTableModel model = (DefaultTableModel)RentTable.getModel();
       int MyIndex = RentTable.getSelectedRow();
       RentIdTxt.setText(model.getValueAt(MyIndex,0).toString());
       RegTxt.setText(model.getValueAt(MyIndex,1).toString());
       CustomerNameComboBox.setSelectedItem(model.getValueAt(MyIndex,2).toString());
       FeesTxt.setText(model.getValueAt(MyIndex,5).toString());
    }//GEN-LAST:event_RentTableMouseClicked

    private void RentsPrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentsPrintBtnActionPerformed
        try{
            RentTable.print();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_RentsPrintBtnActionPerformed
  
        //current date
       java.util.Date RentDate1,ReturnDate1;
       java.sql.Date MyRentDate,MyReturnDate;
    private void RentsSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentsSaveBtnActionPerformed
        //Checking missing informaiton
        if(RentIdTxt.getText().isEmpty() || FeesTxt.getText().isEmpty() || RegTxt.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "Mising Information");
         }
          else{
               try{
                   //for rentdate
                   RentDate1 = RentDate.getDate();
                   MyRentDate = new java.sql.Date(RentDate1.getTime());
                   //for returndate
                   ReturnDate1 = ReturnDate.getDate();
                   MyReturnDate = new java.sql.Date(ReturnDate1.getTime());

                    //Desktop url connection with sql
                    connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cardb","root","123456s.");

                    //sql command for add with insert into
                    PreparedStatement add = connection.prepareStatement("insert into renttbl values(?,?,?,?,?,?)");

                    //assigment parameters
                    add.setInt(1,Integer.valueOf(RentIdTxt.getText()));
                    add.setString(2, RegTxt.getText());
                    add.setString(3,CustomerNameComboBox.getSelectedItem().toString());
                    add.setDate(4, MyRentDate);
                    add.setDate(5,MyReturnDate );
                    add.setInt(6,Integer.valueOf(FeesTxt.getText()));

                    //execute for keep the memory
                    int row = add.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Car Rented Successfully");
                    DisplayRents();
                    UpdateCar();
                    DisplayCars();                  
                   

                    }catch(Exception e){
                         ///print error
                         e.printStackTrace();
                    }
            }
    }//GEN-LAST:event_RentsSaveBtnActionPerformed
    private void Reset()
    {
        
        RentIdTxt.setText("");
        RegTxt.setText("");
        CustomerNameComboBox.setSelectedIndex(-1);
        FeesTxt.setText("");
     
     
    }
    private void RentsResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentsResetBtnActionPerformed
       Reset();
    }//GEN-LAST:event_RentsResetBtnActionPerformed

    //it is have to be available to booked
    private void UpdateCar()
    {
           try{

                    //Desktop url connection with sql
                    connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cardb","root","123456s.");
                    String reg = RegTxt.getText();
                    String CarStatus ="Booked";
                    //for edit data command
                    String Query ="Update cartbl set status='"+CarStatus+"'where regisNum='"+reg+"'";
                    Statement Add = connection.createStatement();
                    Add.executeUpdate(Query);
                    JOptionPane.showMessageDialog(this, "Car Booked Succesfully");
                    DisplayCars();
                    Reset();
                    
                   
                    //PreparedStatement  update = connection.prepareStatement(query);
                    //like assigment
//                    update.setString(3, CarStatus);
//                    
//                    update.setString(4, registration);
//                    
//                    //execute for keep the memory
//                      int rowsUpdated = update.executeUpdate();
//            
//                    if (rowsUpdated > 0) {
//                        JOptionPane.showMessageDialog(this, "Car Updated Successfully");
//                        // Refresh table
//                        DisplayCars();
//                        Reset();
//                    } else {
//                        JOptionPane.showMessageDialog(this, "Failed to update car");
//                    }
                    
                    

                    }catch(Exception e){
                         ///print error
                         e.printStackTrace();
                    }       
    }
    private void RentsEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentsEditBtnActionPerformed
          if(RentIdTxt.getText().isEmpty() || FeesTxt.getText().isEmpty() || RegTxt.getText().isEmpty()  || CustomerNameComboBox.getSelectedIndex()==-1){
          JOptionPane.showMessageDialog(this, "Select the Rent TO Be Updated");
         }
          else{
               try{
                   //for rentdate
                   RentDate1 = RentDate.getDate();
                   MyRentDate = new java.sql.Date(RentDate1.getTime());
                   //for returndate
                   ReturnDate1 = ReturnDate.getDate();
                   MyReturnDate = new java.sql.Date(ReturnDate1.getTime());

                    //Desktop url connection with sql
                    connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cardb","root","123456s.");
                    int rent_ıd = Integer.valueOf(RentIdTxt.getText());
                    //for edit data command
                     String query ="Update renttbl set CarReg=?,CustomerName=?,RentDate=?,ReturnDate=?,RentFee=? where RentId=?";
                    PreparedStatement  update = connection.prepareStatement(query);
                    //like assigment
                    update.setString(1, RegTxt.getText());
                    update.setString(2, CustomerNameComboBox.getSelectedItem().toString());
                    update.setDate(3, MyRentDate);
                    update.setDate(4,MyReturnDate );
                    update.setString(5,FeesTxt.getText());
                    update.setInt(6, rent_ıd);
                    
                    //execute for keep the memory
                      int rowsUpdated = update.executeUpdate();
            
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(this, "Rents Updated Successfully");
                        // Refresh table
                        DisplayRents();
                        DisplayCars();
                        Reset();
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to update car");
                    }
                    
                    

                    }catch(Exception e){
                         ///print error
                         e.printStackTrace();
                    }
            }
    }//GEN-LAST:event_RentsEditBtnActionPerformed

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
      new Customers().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_CustomerMouseClicked

    private void CarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsMouseClicked
      new Cars().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_CarsMouseClicked

    private void ReturnCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnCarMouseClicked
      new Returns().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ReturnCarMouseClicked

    private void LogOut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut1MouseClicked
      new LogIn().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_LogOut1MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
     System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cars;
    private javax.swing.JTable CarsTable;
    private javax.swing.JLabel Customer;
    private javax.swing.JComboBox<String> CustomerNameComboBox;
    private javax.swing.JTextField FeesTxt;
    private javax.swing.JLabel LogOut1;
    private javax.swing.JTextField RegTxt;
    private com.toedter.calendar.JDateChooser RentDate;
    private javax.swing.JTextField RentIdTxt;
    private javax.swing.JTable RentTable;
    private javax.swing.JButton RentsEditBtn;
    private javax.swing.JButton RentsPrintBtn;
    private javax.swing.JButton RentsResetBtn;
    private javax.swing.JButton RentsSaveBtn;
    private javax.swing.JLabel ReturnCar;
    private com.toedter.calendar.JDateChooser ReturnDate;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
